### ISSUE TITLE
Error getting video information is live

### ISSUE THREAD

**Issue by balasratran** [markovcd/YoutubeSnoop#1]
>  var v = Youtube.Video("DExUQUzgARg").RequestAllParts();
            Console.WriteLine(v.ChannelTitle);

`Error converting value "Cg0KC0RFeFVRVXpnQVJn" to type 'System.Nullable`1[System.Int64]'. Path 'items[0].liveStreamingDetails.activeLiveChatId', line 1, position 3795.`

**Comment by markovcd** [comment]
Thanks for input. Issue is now fixed:
https://github.com/markovcd/YoutubeSnoop/commit/2379bd133ab10e3af32ae2b5c5d061642a49aa4b
