### ISSUE TITLE
Get value field Status.Embeddable & Snippet.LiveBroadcastContent

### ISSUE THREAD

**Issue by balasratran** [markovcd/YoutubeSnoop#2]
`var video = Youtube.Video("video id").RequestAllParts();`
How can I get LiveBroadcastContent and Embeddable field information?
Looking forward to hearing from you soon. Thank you

**Comment by balasratran** [comment]
I added these two value fields.
File: YoutubeVideo.cs
`_liveBroadcastContent = response.Snippet.LiveBroadcastContent.Value;`
` if (response.Status != null)
            {
                _embeddable = response.Status.Embeddable;
            }`

**Comment by markovcd** [comment]
Great idea to include all the details returned by API. Fixed in commit https://github.com/markovcd/YoutubeSnoop/commit/597cdaf6edfdaf3beb5bfedf4deb825accec3521.
