### ISSUE TITLE
Additional param key API

### ISSUE THREAD

**Issue by balasratran** [markovcd/YoutubeSnoop#3]
Currently I see you are trying to key the API into the _apiKey variable. I think you should let the user pass an api value from the outside. Please review and let me know your opinion on this issue. Thank you

**Comment by markovcd** [comment]
That's probably a good idea. Added such possibility in commit https://github.com/markovcd/YoutubeSnoop/commit/f1f2df6d9fc9eee481385b82d09cf3c2dea6a6f5.
